# Generated by Django 5.1.1 on 2024-10-17 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostContent',
        ),
    ]
