# Generated by Django 5.1.1 on 2024-10-02 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='published_date',
        ),
    ]
