# Generated by Django 5.1.3 on 2024-12-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_rename_name_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='group_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
