# Generated by Django 5.1.3 on 2024-12-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_post_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='group_id',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
    ]
