# Generated by Django 5.1.3 on 2024-12-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_message_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_reply',
            field=models.BooleanField(default=False),
        ),
    ]
