# Generated by Django 5.1.3 on 2024-12-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_message_is_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_room',
            name='group_id',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
    ]
