# Generated by Django 5.1.3 on 2024-12-11 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_chat_room_group_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat_room',
            name='group_id',
        ),
    ]
