# Generated by Django 5.1.3 on 2024-12-11 14:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_remove_chat_room_group_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_room',
            name='members',
            field=models.ManyToManyField(related_name='Members', to=settings.AUTH_USER_MODEL),
        ),
    ]
