# Generated by Django 5.1.4 on 2024-12-11 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_grouppost_groupcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouppost',
            name='author',
        ),
        migrations.RemoveField(
            model_name='grouppost',
            name='group_id',
        ),
        migrations.DeleteModel(
            name='GroupComment',
        ),
        migrations.DeleteModel(
            name='GroupPost',
        ),
    ]
