# Generated by Django 5.1.3 on 2024-12-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
