# Generated by Django 5.1.3 on 2024-12-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_scheduler', '0002_alter_calendarevent_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='is_attended',
            field=models.BooleanField(default=False),
        ),
    ]
