# Generated by Django 5.1.3 on 2024-12-09 03:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_scheduler', '0003_calendarevent_is_attended'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarevent',
            name='is_attended',
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='attendees',
            field=models.ManyToManyField(related_name='attended_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
