# Generated by Django 5.1.3 on 2024-12-09 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_scheduler', '0004_remove_calendarevent_is_attended_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarevent',
            name='attendees',
        ),
    ]
